### ISSUE TITLE
Just some comments

### ISSUE THREAD

**Issue by Westirasuto** [Samsterr/sir-squirrel-assistant#41]
Really good software, here are some comments and advices:
1. May be we can prioritize to pick the "question mark" event, and then the battle. It reduces the time it takes to complete a mirror dungeon.  I think is very difficult to scan for the best path of the mirror dungeon, so I think we can just scan the components that we can choose? like this:
![image](https://github.com/user-attachments/assets/95ee2eda-ba55-42ac-82a2-2b25f6ec092c)

If there is no "question mark" event or we cannot click on the "question mark" event, we can just randomly click on the event that we can go. Or we can prioritize to click on the "regular encounter", then the "focused encounter" and "elite encounter".

2.  Since every time when we get into "sinner picking UI", it automatically clear selection and follow the .json file squad_order to repick the sinner again. Therefore, maybe we can add a new feature to detect the participant limit? Which only clear selection and reselect If the participant limit is not 6/6 or 12/12.
![image](https://github.com/user-attachments/assets/9ed2487b-bb47-49d4-a6f0-9df0d3ba8bd9)

3. If the requirement 1. is satisfied, I think we can prioritize the pack selection to select the "Hell's chicken" pack (only floor 2). 
![image](https://github.com/user-attachments/assets/f8e08b2a-cf8f-40c1-b4c2-e5cf26bc4ce9)

The EGO gift from hell's chicken pack are very strong. If we are able to obtain these gifts, it can speed up the whole game. 
![image](https://github.com/user-attachments/assets/5139c9f8-077e-4423-9d08-0f025c852ca1)

4. Auto-merging strong ego gift could be useful? Like bloody mist (successful rate 100%, but need specific ego gifts to merge) and Glimpse of Flames (90% successful rate, but only needs 3+3+2 ego gift to merge)

5. Avoid picking bad theme pack would also be a good feature. (not sure whether it can be done by just removing the text from f1/f2/f3/f4.txt)
For example:
Theme packs have long term battle:
![image](https://github.com/user-attachments/assets/50c9d5db-6549-46c7-a52e-d551a74fb3fb) 
![image](https://github.com/user-attachments/assets/4e3ace0a-9a62-42b4-a6bf-8b143b418fe4) 
![image](https://github.com/user-attachments/assets/0e705c9a-0d57-425d-aa19-0ffe95c87ac4) 
![image](https://github.com/user-attachments/assets/431d5710-07b7-4e3b-8417-9fa76d80b8ed)
![image](https://github.com/user-attachments/assets/b47d0bb4-7d37-4f8d-8d17-571d56140601)
![image](https://github.com/user-attachments/assets/f4a011ee-fb53-47eb-a2e0-be5672d1a349)

Theme packs that Boss has second life:
![image](https://github.com/user-attachments/assets/de1882df-2a58-4749-8a78-aa0d49517efa)
![image](https://github.com/user-attachments/assets/63a8aeb2-d45b-4cab-bc34-c7e5ff9dbab7)
![image](https://github.com/user-attachments/assets/f09c218e-d0ab-4a57-91a5-552ab2cbbd2e)

Theme packs that not good for auto-combat (basically the packs have “Skin Prophet”, "Doomsday Calendar" and "Dream-Devouring Siltcurrent":
![image](https://github.com/user-attachments/assets/810931e4-3834-4745-86a6-9db5b9ab5616)
![image](https://github.com/user-attachments/assets/088dd1bb-d6c9-446d-a537-ff7ff56538ac)
![image](https://github.com/user-attachments/assets/ed6a61a3-2deb-45a5-b7b5-2c84122c768e)
![image](https://github.com/user-attachments/assets/b1dd550b-2b9e-4bb5-a1e6-207b50ee0539)
![image](https://github.com/user-attachments/assets/7941c59e-ca2a-4efd-a17e-fea9b2b74163)
![image](https://github.com/user-attachments/assets/19c3d0d2-4f45-4dc0-a7f7-4a17c8fd4e80)

**Comment by Samsterr** [comment]
@Westirasuto thanks for taking the time to give some feedback which i will address.

For number 1 that was how i initially wanted to do the detection of the nodes for mirror dungeon because events are generally faster but due to how they are displayed currently its not that consistent to detect for the node type as there's some parallax to it.

for number 2 that is something i do want to implement which will speed up time but I'm currently more focused on updating sir squirrel for MD5 when that releases. i will take this into consideration and will probably drop in a later update.

for number 3, pack priority is already dictated by you, you can change the order of the packs in f1/f2/f3/f4 respectively with earlier entries being the higher priority. however this will only take into effect only if there is no ego gift of the same type you are running.

for number 4, auto merging was noted to be a bit too troublesome to implement due to the amount of checks and for now at least MD normal is quite beatable regardless. i might consider implementing it if i have a more easier way to do it and have time to test it.

for number 5, the packs you mentioned are already being excluded, but now that you mention it i think i did miss crawling abyss pack for f4. as per number 3 you can already shift these packs to the bottom but as the current logic is to prioritise packs that have status ego gifts matching provided the unwinrateable packs arent present. the list is only used when the offending packs are present.

Hope these give you a better insight of some of the constrains i'm working with as some things which we can see and understand the flow might require a lot more work to get the program to see things as we do. some of the features are stuff i do want to implement but simply cant because i haven't conceived of a proper way to do it that translate into programming
